### ISSUE TITLE
Capture Sample Rate

### ISSUE THREAD

**Issue by mcehs** [ericgibert/supersid#7]
Hi, I was wondering why alsa does not capture at a sample rate of 96000 (required for North American SID monitoring), and how to enable that functionality.  Thank you!

**Comment by ericgibert** [comment]
Hi mcehs,

Did you setup the sample rate in the .cfg file as follow:
audio_sampling_rate = 96000

To confirm that you Linux/ALSA is recognized, you can run supersid/sampler.py by itself: it will list all the possible sampling rates. Check out that 96000 is supported.

Best regards,

Eric
